version: '3'
services:
  web:
    build: ./app
  proxy:
      build: ./web/gamepicker
      ports:
         - "80:80"
  mongo:
      image: "mongo:3.4-xenial"
      volumes:
          - ./mongo/data:/data/db
      restart: always
