version: '3'
services:
  app:
    build: ./app
  proxy:
      build: ./web/proxy
      ports:
        - "80:80"
  devserver:
      build: ./web/gamepicker
      ports:
        - "8080:8080"
      volumes:
        - ./web/gamepicker/:/app 
      command: /bin/sh -c "npm run dev"
  mongo:
      image: "mongo:3.4-xenial"
      volumes:
          - ./mongo/data:/data/db
      restart: always
